/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddExercise: typeof import('./src/components/AddExercise.vue')['default']
    Card1: typeof import('./src/components/Card1.vue')['default']
    copy: typeof import('./src/components/HomeWorkouts copy.vue')['default']
    CreateExercise: typeof import('./src/components/CreateExercise.vue')['default']
    ExerciseCard: typeof import('./src/components/ExerciseCard.vue')['default']
    ExerciseCardList: typeof import('./src/components/ExerciseCardList.vue')['default']
    ExerciseHistoryTable: typeof import('./src/components/ExerciseHistoryTable.vue')['default']
    HomeAddWorkoutItem: typeof import('./src/components/HomeAddWorkoutItem.vue')['default']
    HomeDashboard: typeof import('./src/components/HomeDashboard.vue')['default']
    HomeExercises: typeof import('./src/components/HomeExercises.vue')['default']
    HomeWorkoutItem: typeof import('./src/components/HomeWorkoutItem.vue')['default']
    HomeWorkouts: typeof import('./src/components/HomeWorkouts.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RepsAndWeightStepper: typeof import('./src/components/RepsAndWeightStepper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stepper: typeof import('./src/components/Stepper.vue')['default']
    StepperSlides: typeof import('./src/components/StepperSlides.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanField: typeof import('vant/es')['Field']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanRollingText: typeof import('vant/es')['RollingText']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VantIcon: typeof import('vant/es')['tIcon']
  }
}
